### ISSUE TITLE
theSlate will not open on my Microsoft Surface Go

### ISSUE THREAD

**Issue by reiyua** [vicr123/theSlate#4]
I have literally installed theSlate a couple minuites ago, and it wont open when i click the icon.

I am running Windows 10 Home on the following specs

![image](https://user-images.githubusercontent.com/11124303/55031072-dbba9a00-5061-11e9-859e-7f65672856c3.png)

**Comment by vicr123** [comment]
Can I get some more information please? What happens when you click the icon? What about if you open up the executable file directly?

**Comment by reiyua** [comment]
Hi, i have tried running the executable directly, via the start menu, running as administrator, and restarting the compter.

Sent from Mail for Windows 10

**Comment by vicr123** [comment]
What happens specifically when you try to open it? Is there an entry in the Task Manager after you open it?

**Comment by reiyua** [comment]
Theres no task entry within task manager in both “details” and “simple mode”

Sent from Mail for Windows 10

**Comment by vicr123** [comment]
What happens if you try to run it through the command prompt?

**Comment by reiyua** [comment]
Still nothing.

Sent from Mail for Windows 10

**Comment by reiyua** [comment]
Command Propmpt reutrns no errors like when you would run any other program from command prompt.

**Comment by vicr123** [comment]
Are you trying to run the installer, an installed version of theSlate or a portable version?

**Comment by reiyua** [comment]
I am trying to run the installed version.

Sent from Mail for Windows 10

**Comment by vicr123** [comment]
Alright, I've been able to reproduce the issue so a fix should be coming soon :)

**Comment by reiyua** [comment]
Thanks Victor.

**Comment by reiyua** [comment]
Hey Victor, for some reason, it still wont open for me, i am still running on the same specs.

**Comment by vicr123** [comment]
Hi, I thought I fixed this a while back... I'm not exactly sure why it's crashing on your computer specifically when you fire it up.

Does the portable version work for you?

**Comment by reiyua** [comment]
Hi Victor,


i tried looking for the portable version and i am unable to find it.

Could you send me a direct link please?

**Comment by vicr123** [comment]
You'll find it in the releases of this repository.

**Comment by reiyua** [comment]
Hi Victor,

I have tried running the portable version, it does absoloutely nothing, and i have checked things like command prompt and task manager entries

**Comment by vicr123** [comment]
Can you check to see if Entertaining Mines runs on your computer? https://github.com/vicr123/entertaining-mines

**Comment by reiyua** [comment]
Hey Victor, 

Entertaining Mines runs perfectly for me with no problems whatsoever

**Comment by vicr123** [comment]
Must be something wrong I'm doing in theSlate then :/

**Comment by reiyua** [comment]
Anything i could do on my end?

**Comment by vicr123** [comment]
Is your system set to light mode or dark mode?

**Comment by reiyua** [comment]
Hi Victor,

My system is set to use light mode,

**Comment by vicr123** [comment]
Mind setting it to dark mode and seeing if that makes a difference?
